#Minecraft server properties
#Sat Nov 22 10:52:46 UTC 2025
accepts-transfers=false
allow-end=true
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=normal
do-daylight-cycle=true
do-entity-drops=true
do-fire-tick=true
do-insomnia=true
do-mob-spawning=true
do-tile-drops=true
enable-code-of-conduct=false
enable-command-block=false
enable-command-block-output=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
keep-inventory=true
level-name=world
level-seed=
level-type=minecraft\\\:normal
log-ips=true
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=wGqVU9ncQ5I1OjxykAnotMsSWY2xyaj1mNFZ8wUB
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
min-build-height=0
motd=Managed by Web UI - Minecraft Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=admin
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-name=Involvex Minecraft Server
server-port=25565
simulation-distance=15
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=15
white-list=false
